// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

/*
Package proto is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

It is generated from these files:
	api.proto
*/
package proto

import (
	"context"

	bm "go-common/library/net/http/blademaster"
	"go-common/library/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

// StreamServiceBMServer is the server API for StreamService service.
type StreamServiceBMServer interface {
}

var StreamServiceSvc StreamServiceBMServer

// RegisterStreamServiceBMServer Register the blademaster route
func RegisterStreamServiceBMServer(e *bm.Engine, server StreamServiceBMServer) {
	StreamServiceSvc = server
}
