// Code generated by protoc-gen-ecode v0.1, DO NOT EDIT.
// source: ecode.proto

package proto

import (
	"go-common/library/ecode"
)

// to suppressed 'imported but not used warning'
var _ ecode.Codes

// AccountErrCode ecode
var (
	AccountNotLogin = ecode.New(35002)
)
